import { Battery, Wind, Leaf, TrendingDown, Shield, Check, Flame, Phone, Mail, MapPin, Star, ChevronDown, ChevronUp, ArrowRight, ArrowUp, Clock, Package, Zap, Heart, Users, Camera, Play, Menu, X, Instagram, MessageCircle, ExternalLink } from "lucide-react";

export const Icons = {
  Battery,
  Wind,
  Leaf,
  TrendingDown,
  Shield,
  Check,
  Flame,
  Phone,
  Mail,
  MapPin,
  Star,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowUp,
  Clock,
  Package,
  Zap,
  Heart,
  Users,
  Camera,
  Play,
  Menu,
  X,
  Instagram,
  MessageCircle,
  ExternalLink,
};
